ghc-stage2: panic! (the 'impossible' happened)
  (GHC version 8.5.20180216 for x86_64-unknown-linux):
	ASSERT failed!
  [a_a1WO]
  [a_a1WP]
  [@a_a1WP]
  Call stack:
      CallStack (from HasCallStack):
        callStackDoc, called at compiler/utils/Outputable.hs:1150:37 in ghc:Outputable
        pprPanic, called at compiler/utils/Outputable.hs:1206:5 in ghc:Outputable
        assertPprPanic, called at compiler/basicTypes/DataCon.hs:896:70 in ghc:DataCon

Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug

